export { Menu } from './Menu/Menu';
export { Hero } from './Hero/Hero';
export { About } from './About/About';
export { Title } from './UI/Title/Title';
export { Header } from './Header/Header';
export { Contact } from './Contact/Contact';
export { Courses } from './Courses/Courses';
export { Button } from './UI/Button/Button';
export { Subtitle } from './UI/Subtitle/Subtitle';
export { CourseItem } from './CourseItem/CourseItem';
export { Navigation } from './Navigation/Navigation';
export { Advantages } from './Advantages/Advantages';
export { ContactForm } from './ContactForm/ContactForm';
export { Testimonials } from './Testimonials/Testimonials';
export { ProgrammItem } from './ProgrammItem/ProgrammItem';
export { LinkWithArrow } from './UI/LinkWithArrow/LinkWithArrow';
export { AdvantagesCard } from './AdvantagesCard/AdvantagesCard';
// export { Testimonials } from './Testimonials/Testimonials';
